spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.url=jdbc:postgresql://localhost:5432/image-uploader
spring.jpa.hibernate.ddl-auto=update

aws.s3.accessKeyId=minio
aws.s3.secretAccessKey=minio123
aws.s3.bucketName=image-uploader